### PR TITLE
Added a few methods to help complete the API

### PR DESCRIPTION
**Pull request by upwebdesign**
These methods are required for us to make this package production ready.

### CODE REVIEW

**Comment by upwebdesign** [comment]
@slakbal Let me know if you can review and merge these changes in so I can release a new version of our software! Thanks!

**Comment by slakbal** [comment]
@upwebdesign hey Jesse, I don't mind pulling these in for you. But note that I'm busy phasing this package out since I have a newer version and will soon mark it as end of life in packagist. 

You can find the new version here: [slakbal/gotowebinar](https://github.com/slakbal/gotowebinar)

So it's probably better for you to start moving over. I'm using the new version already in my projects and I feel it is as stable as this older package.

**Comment by slakbal** [comment]
@upwebdesign ... merged and a new release created. Should be ready for composer update. Let me know regarding the above package, otherwise, you can also take over/fork the old code and carry on with that. But would prefer to continue with you on the new package. The more the better with the maintenance of it. :)

**Comment by upwebdesign** [comment]
@slakbal Right... you know, it may be a good idea to mark this package as deprecated and provide a link to the new package. I was a bit confused as to what was the most updated package. I will update to use the newer package! Thanks!

**Pull request merged**
