### PR TITLE
Master

### PR DESCRIPTION
**Pull request by upwebdesign**
This allows for additional default and custom fields per GoToWebinar’s
API documentation when registering an attendee, such as phone, city and
state. The use of the collect helper eliminates the need for the
Attendee Entity class.

### CODE REVIEW

**Comment by upwebdesign** [comment]
@slakbal This has been tested on my end. Let me know if you see any changes need. If you are not accepting pull requests, please let me know so I can use my fork in my project.

**Comment by slakbal** [comment]
@upwebdesign AHA I see what you are doing here... I agree with your statement: "_This allows for additional default and custom fields per GoToWebinar’s API documentation when registering an attendee, such as phone, city and state._"

I noticed on the API they have been adding more fields. I think I'm going to remove all the object instantiation completely and just pass it in as per you last PR then I clean it up even further to remove the Entities.

How are you looking on time or is it a burning issue for you, then I can tackle it in the new version as soon as I have an hour to put in?

**Comment by upwebdesign** [comment]
@slakbal Thank you for the quick response! Yes, this is a burning issue for us. If you could merge it in my pull request now, I would be grateful. I am happy you found some clarity in the pull request and looking forward to seeing the develop branch make its way to master!

**Comment by slakbal** [comment]
@upwebdesign Done, you should be able to update now your project.

**Comment by upwebdesign** [comment]
@slakbal Yep, just updated. Thanks again!

**Comment by slakbal** [comment]
@upwebdesign - Hi there, wanted to let you know that my new version of my package is available. It is however a new repo also because of the company's name change etc. . You can find it here: https://github.com/slakbal/gotowebinar

I will start to fade away the old package https://github.com/slakbal/citrix

**Comment by upwebdesign** [comment]
@slakbal Thanks for the update!

**Pull request merged**
